# Generated by Django 3.1.3 on 2021-02-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Question',
            name='create_date',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
