# Generated by Django 3.1.3 on 2021-02-19 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create',
            new_name='create_date',
        ),
    ]
